{
 "title": "groviepi-exporter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "reset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "light",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_light" }
   ]
  },
  {
   "title": "Loudless",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_sound" }
   ]
  },
  { "title": "Barometer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "grovepi_barometer_pressure" }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "grovepi_barometer_temperature" }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "grovepi_barometer_humidity" }
   ]
  },
  { "title": "hcho_sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ppm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_ppm" }
   ]
  },
  {
   "title": "sensor_value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_sensor_value" }
   ]
  },
  {
   "title": "Rs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_hcho_rs" }
   ]
  },
  {
   "title": "Sensitivity Curve",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(grovepi_hcho_rs/grovepi_hcho_r0)/grovepi_hcho_ppm"
    }
   ]
  },
  { "title": "dht_sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_dht_temperature" }
   ]
  },
  {
   "title": "humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grovepi_dht_humidity" }
   ]
  }
 ]
}